### ISSUE TITLE
Optimize tests

### ISSUE THREAD

**Issue by laniakea64** [NoahTheDuke/vim-just#27]
Currently it is rather slow to run the test suite.  And it will get even slower as we add more test cases.

Two possible ideas for how we could speed it up:

1) Since each test file seems to take about the same amount of time, consider consolidating some of the existing test cases into fewer files.

2) Change the test runner to perform the `convert-to-html`s in parallel (with # of parallel jobs = # of physical CPU cores?), and only after all outputs are generated, only then go through and `colordiff` each output compared to its expected.  The `colordiff` runs should stay sequential, to avoid any potential for confusion due to out-of-order output.

Maybe worth doing both?

**Comment by NoahTheDuke** [comment]
Give either of these a try in a PR and we can discuss improvements.

I suspect consolidation of files will be a best approach. I split them up initially because I don't want earlier syntax to influence later syntax. It's hard to test individual pieces if we have to worry about muddying across sections. I suspect your recent changes have helped with that.

Maybe the kitchen sink file could be a new test file?

**Comment by NoahTheDuke** [comment]
Oh, wonderful. I missed you added it to the test folder. Hell yeah, if you feel like there aren't any overlaps of syntax (places where earlier forms affects the syntax highlighting of the current form), cut out any test files that you think overlap.

**Comment by nk9** [comment]
Oh, and another obvious optimization: don't call `convert-to-html` at all if `x.html` is newer than `x.just`.

**Comment by NoahTheDuke** [comment]
Oooooh interesting! Is .output processing a bunch of text noise from vim? Might be the reason. If that's reducing the time by that much, open a PR with it!
