### ISSUE TITLE
Alias syntax highlighting

### ISSUE THREAD

**Issue by casey** [NoahTheDuke/vim-just#5]
Since the left hand side and right hand side of aliases are recipe names, it might make sense to assign them to the `Function` group, so there's highlighted the same as recipe names in recipe declarations.

I started working on this, but I ran in to a bunch of stuff that confused me. In particular, I created the following test in `tests/cases/alias.just`:

```
alias foo := bar
```

And got the following output:

```html
<span class="Keyword">alias</span><span class="Keyword"> </span><span class="Identifier">foo</span><span class="Keyword"> </span><span class="Operator">:=</span> bar
```

It looks like whitespace is being highlighted as a `Keyword`, which, since I know nothing about vim syntax highlighting, I wasn't sure if it was correct or not.

The highlighting that would be ideal is probably something like this:

```html
<span class="Keyword">alias</span> <span class="Function">foo</span> <span class="Operator">:=</span> <span class="Function">bar</span>
```

**Comment by NoahTheDuke** [comment]
I don't think I realized that every alias is a function! Got tunnel-vision from focusing on GRAMMAR.md, hah. I just pushed a somewhat big change with tests, which includes that exact test. I changed how `alias` works so it's just a simple "keyword" instead of matching more complex logic, but I can re-implement that logic so we can highlight these.

New behavior: `<span class="Keyword">alias</span> foo <span class="Operator">:=</span> bar`

**Comment by casey** [comment]
There is some weirdness here! You can actually have a recipe called alias:

```
alias:
  echo foo
```

The parser looks ahead and if it sees `alias IDENT :=` it knows it's an alias, otherwise it's a recipe.

**Comment by NoahTheDuke** [comment]
Just pushed 05ce5fa, which adds a proper `justFunction` class to the syntax, which is now used in aliases. Let me know if that works for you.

**Comment by casey** [comment]
Looks great!
